- src/main/c/jpy_jtype.c
Partial #7
If two java overloads existed, one taking an int[] and one a long[], jpy used to always use the int[] method even if you passed in data with long precision. This should work now
```java
myMethod(int[] a) {
// <do whatever>
}
myMethod(long[] a) {
// <do whatever>
}
```
> long array fix

- src/main/c/jni/org_jpy_PyLib.c
- src/main/c/jni/org_jpy_PyLib.h
- src/main/c/jpy_jmethod.c
- src/main/c/jpy_jtype.c
- src/main/c/jpy_module.c
- src/main/c/jpy_module.h
- src/main/java/org/jpy/PyLib.java
- src/main/java/org/jpy/PyObjectReferences.java
- src/test/java/org/jpy/PyLibTest.java
There is one exceptional case to deal with, allowing Java to hold and
keep the GIL when it wants it, such as for cleanup work. Now Java can
grab the GIL if it needs it, without a full trip into python and back
again.
> Release the GIL while in Java, with a special method to deliberately acquire it

- src/main/c/jpy_compat.h
- src/main/c/jpy_jobj.c
Follow up to https://github.com/jpy-consortium/jpy/pull/14
> Guard Py_SET_REFCNT to Python 3.9+

- src/main/c/jpy_jtype.c
C char type on arm64 is unsigned, resulting in negative Java byte for values bigger than 127
> Fix a JPY byte conv issue on arm64

- src/main/c/jpy_jtype.c
> Support creation of zero-sized primitive Java arrays

- jpyutil.py
This adds an optional check when the `java-utilities` [package](https://pypi.org/project/java-utilities/) is installed.
When java-utilities is not installed, it behaves as it does today:
```
Python 3.10.7 (main, Sep  7 2022, 00:00:00) [GCC 12.2.1 20220819 (Red Hat 12.2.1-1)] on linux                                                                                    
Type "help", "copyright", "credits" or "license" for more information.                                                                                                           
>>> import jpyutil                                                                                                                                                               
>>> jpyutil.init_jvm() …
```
> Add Java process lookup for 'java.home' in find_jvm_dll_file()

- .github/env/Linux/requirements.txt
- .github/workflows/build.yml
- src/main/c/jni/org_jpy_PyLib.c
- src/main/c/jpy_compat.h
- src/main/c/jpy_jobj.c
See https://docs.python.org/3.11/whatsnew/3.11.html#whatsnew311-c-api-porting
Added Py_SET_TYPE compatibility
Added Py_SET_SIZE compatibility
Added PyFrame_GetCode compatibility
Added explicit patchelf dependency instead of relying on system binary, not included by default (see https://github.com/pypa/auditwheel/issues/386, https://github.com/pypa/auditwheel/pull/403)
Added Python 3.11 CI logic
Fixes #95
> Python 3.11 compatibility

- src/main/c/jni/org_jpy_PyLib.c
> Check for exception in getInt/Long/DoubleValue()

- .github/docker/docker-bake.hcl
- .github/env/Linux/requirements.txt
- .github/env/Windows/requirements.txt
- .github/env/macOS/requirements.txt
- .github/workflows/build.yml
distutils is no longer provided on python 3.12+, see https://peps.python.org/pep-0632/#backwards-compatibility.
Fixes #115
> Python 3.12 build

- .github/env/Linux/requirements.txt
- .github/env/Windows/requirements.txt
- .github/env/macOS/requirements.txt
- .github/workflows/build.yml
- README.md
- jpyutil.py
Fix Mac OSX + OpenJDK builds where `JAVA_HOME` contains `libexec` but not `lib`.
Build for Python 3.12
Resolves #118
> Fix Mac OSX + OpenJDK builds where `JAVA_HOME` contains `libexec` but not `lib`

- .github/workflows/build.yml
This ensures that python 3.8+ produce universal2 wheels (python 3.6, 3.7 doesn't support M1).
Fixes #110
> Build universal2 wheels for macos

- .gitignore
- README.md
- doc/reference.rst
- jpyutil.py
- setup.py
- src/main/c/jni/org_jpy_PyLib.c
- src/main/c/jpy_conv.c
- src/main/c/jpy_conv.h
- src/main/c/jpy_jmethod.c
- src/main/c/jpy_jobj.c
- src/main/c/jpy_jtype.c
- src/main/c/jpy_module.c
- src/test/java/org/jpy/EmbeddableTestJunit.java
- src/test/java/org/jpy/JavaReflectionTest.java
- src/test/java/org/jpy/LifeCycleTest.java
- src/test/java/org/jpy/PyLibTest.java
- src/test/java/org/jpy/PyLibWithSysPathTest.java
- src/test/java/org/jpy/PyModuleTest.java
- src/test/java/org/jpy/PyObjectTest.java
- src/test/java/org/jpy/PyProxyTest.java
- src/test/java/org/jpy/TestStatePrinter.java
- src/test/java/org/jpy/fixtures/TypeConversionTestFixture.java
- src/test/python/jpy_exception_test.py
- src/test/python/jpy_overload_test.py
- src/test/python/jpy_translation_test.py
- src/test/python/jpy_typeconv_test.py
- src/test/python/jpy_typeconv_test_pyobj.py
- Fix a bug in `cast`
- Add an `as_jobj` method to convert a Python value to a Java object of the given type. This leverages the existing `JPy_AsJObjectWithType` method.
- Update some tests to match current behavior (e.g. returning `Byte` instead of `Integer`)
- More logging during tests
- Fixed failing `hashNegativeOne` test
- Replace incorrect `return Py_NONE`s with `Py_RETURN_NONE` (for correct reference counting)
> Function for converting Python values to an explicit Java type

- src/main/c/jni/org_jpy_PyLib.c
- src/main/c/jpy_diag.c
- src/main/c/jpy_jarray.c
- src/main/c/jpy_jfield.c
- src/main/c/jpy_jmethod.c
- src/main/c/jpy_jtype.c
- src/main/c/jpy_verboseexcept.c
Also fixed all the pointer to long conversions that clang 15 considers error by default on MacOS M2
Fixes #143
> Use Py_ssize_t when calculate buffer len

- .github/workflows/check.yml
- setup.py
- src/test/python/jpy_array_test.py
- src/test/python/jpy_eval_exec_test.py
- src/test/python/jpy_exception_test.py
- src/test/python/jpy_modretparam_test.py
1. enable matrix testing:  Py versions - 3.8 to 3.12, Java version: 8, 11, 17, 21, 22. Note only on ubuntu.
2. add a new test case for PR/145 to make up
3. fix one issue - missing JAVA_HOME env, that fails the finding of the JVM dyn libs.
> Enable Matrix testing in CI and add a test for PR/145

- src/main/c/jpy_jobj.c
- src/main/c/jpy_jtype.c
- src/main/c/jpy_module.c
- src/test/java/org/jpy/fixtures/CyclicReferenceChild1.java
- src/test/java/org/jpy/fixtures/CyclicReferenceChild2.java
- src/test/java/org/jpy/fixtures/CyclicReferenceGrandParent.java
- src/test/java/org/jpy/fixtures/CyclicReferenceParent.java
- src/test/java/org/jpy/fixtures/GetTypeFailureChild.java
- src/test/java/org/jpy/fixtures/GetTypeFailureParent.java
- src/test/python/jpy_gettype_test.py
Fixes #142
1. be able to generate Python types from Java classes with complicated cyclic references
2. fix a reference counting issue when a new Python type fails to finalize
3. fix the Python tests and disable the Java tests due to previous changes (years ago) to enable auto PyObjects cleanup in Java.
4. add a limited GH check workflow to run the Python tests on Linux
5. add two new Python test cases
> Delay resolving super classes until referenced 

- .github/workflows/build.yml
- .github/workflows/check.yml
In certain environments, pip fails when it is invoked directly; it requires running it via the `python -m pip`.
```
2024-07-01T15:36:28.7531716Z ##[group]Run pip install --upgrade pip
2024-07-01T15:36:28.7532786Z ␛[36;1mpip install --upgrade pip␛[0m
2024-07-01T15:36:28.7657862Z shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
2024-07-01T15:36:28.7658373Z env:
2024-07-01T15:36:28.7658824Z   pythonLocation: C:\hostedtoolcache\windows\Python\3.8.10\x64
2024-07-01T15:36:28.7659493Z   PKG_CONFIG_PATH: C:\hostedtoolcache\windows\Python\3.8.10\x64/lib/pkgconfig
2024-07-01T15:36:28.7660136Z   Python_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.8.10\x64
2024-07-01T15:36:28.7660710Z   Python2_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.8.10\x64
2024-07-01T15:36:28.7661290Z …
```
> Remove pip upgrade from CI

- .github/workflows/check.yml
- src/main/c/jni/org_jpy_PyLib.c
Fix for https://github.com/python/cpython/issues/109181 introduced lazily computed lineno for traceback object in 3.11.7 and 3.12.1. Tested in a number of Python versions, the change seems to be safe.
The problem was initially reported in https://github.com/deephaven/vscode-deephaven/issues/9
> Get the correct computed tb lineno

- jpyutil.py
OpenJDK 21 on Debian uses `/usr/lib/jvm/default-java/lib/zero/` on Zero-Assembler architectures.
> Find Zero-Assembler OpenJDK 21

- src/main/c/jni/org_jpy_PyLib.c
- src/main/c/jpy_module.h
Python 3.13.0rc1 includes PEP667 (https://peps.python.org/pep-0667) and it made PyEval_GetLocals() no longer behave the same way as in Python 3.12 and older, which could be a bug to report to the cpython team but probably not worth it as it is marked as deprecated  together with PyEval_GetGlobals().
> fix: Make org.jpy.PyLib.getCurrentLocals/Globals work for Python 3.13

- .github/workflows/build.yml
It is currently failing with
```
buildx bake failed with: ERROR: failed to evaluate path "/tmp/dist": lstat /tmp/dist: no such file or directory
```
Likely, a newer version of buildx does not create the directory if it does not exist, or something like that.
It appears this is fixed in buildx 0.19.3 with https://github.com/docker/buildx/pull/2860, but the CI runners are shipping with 0.19.2; we _could_ pin the version of buildx, but creating the directory seems saner for now.
> Fix bake-action build step

- CHANGES.md
- jpyutil.py
This should be considered a partial improvement related to #75.
A fuller solution might involve listing which shared objects were actually loaded via [`dl_iterate_phdr`](https://man7.org/linux/man-pages/man3/dl_iterate_phdr.3.html).
https://github.com/python/cpython/issues/119349
> Improve libpython search with python's sysconfig INSTSONAME

- .github/workflows/build.yml
The collect-artifacts job in the actions/download-artifact step is failing if we don't disable the bake action's artifact uploading. It may due to the use of non-standard characters in the file name; for example `jpy-consortium~jpy~CN2MCZ+7.dockerbuild`, which seems to cause an error "Unable to download artifact(s): Unable to download and extract artifact: Artifact download failed after 5 retries"
See https://github.com/docker/bake-action/tree/v5.11.0?tab=readme-ov-file#environment-variables
> Update docker/bake action
